version: '3.8'

services:
  appointment-service-db:
    image: postgres:15
    container_name: appointment-service-db
    environment:
      POSTGRES_DB: appointment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5444:5432"
    volumes:
      - appointment_service_data:/var/lib/postgresql/data

  diagnostic-service-db:
    image: postgres:15
    container_name: diagnostic-service-db
    environment:
      POSTGRES_DB: diagnostic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5446:5432"
    volumes:
      - diagnostic_service_data:/var/lib/postgresql/data

  pawfectcare-iam-db:
    image: postgres:15
    container_name: pawfectcare-iam-db
    environment:
      POSTGRES_DB: iam
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5439:5432"
    volumes:
      - pawfectcare_iam_data:/var/lib/postgresql/data

  medical-record-service-db:
    image: postgres:15
    container_name: medical-record-service-db
    environment:
      POSTGRES_DB: medicalrecord
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5447:5432"
    volumes:
      - medical_record_service_data:/var/lib/postgresql/data

  pet-owner-service-db:
    image: postgres:15
    container_name: pet-owner-service-db
    environment:
      POSTGRES_DB: petowner
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5442:5432"
    volumes:
      - pet_owner_service_data:/var/lib/postgresql/data

  pet-service-db:
    image: postgres:15
    container_name: pet-service-db
    environment:
      POSTGRES_DB: pet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5441:5432"
    volumes:
      - pet_service_data:/var/lib/postgresql/data

  review-service-db:
    image: postgres:15
    container_name: review-service-db
    environment:
      POSTGRES_DB: review
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5443:5432"
    volumes:
      - review_service_data:/var/lib/postgresql/data

  schedule-service-db:
    image: postgres:15
    container_name: schedule-service-db
    environment:
      POSTGRES_DB: schedule
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5445:5432"
    volumes:
      - schedule_service_data:/var/lib/postgresql/data

  veterinary-service-db:
    image: postgres:15
    container_name: veterinary-service-db
    environment:
      POSTGRES_DB: veterinary
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5440:5432"
    volumes:
      - veterinary_service_data:/var/lib/postgresql/data

volumes:
  appointment_service_data:
  diagnostic_service_data:
  pawfectcare_iam_data:
  medical_record_service_data:
  pet_owner_service_data:
  pet_service_data:
  review_service_data:
  schedule_service_data:
  veterinary_service_data:

