spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1
        - id: pet-management
          uri: lb://pet-management
          predicates:
            - Path=/pet-management/**
          filters:
            - StripPrefix=1
server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/