spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Client Service
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1
        # Pet Service
        - id: pet-management
          uri: lb://pet-management
          predicates:
            - Path=/pet-service/**
          filters:
            - StripPrefix=1
        # Veterinary Service
        - id: veterinary-service
          uri: lb://veterinary-service
          predicates:
            - Path=/veterinarian-service/**
          filters:
            - StripPrefix=1
        # Schedule Service
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/schedule-service/**
          filters:
            - StripPrefix=1
        # Medical Record Service
        - id: medical-record-service
          uri: lb://medical-record-service
          predicates:
            - Path=/medical-record-service/**
          filters:
            - StripPrefix=1
        # Appointment Service
        - id: appointment-management
          uri: lb://appointment-management
          predicates:
            - Path=/appointment-service/**
          filters:
            - StripPrefix=1
        # Review Service
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1
        # Account Service
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1
        # Profile Service
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile-service/**
          filters:
            - StripPrefix=1
        #Diagnosis Service
        - id: diagnostic-service
          uri: lb://diagnostic-service
          predicates:
            - Path=/diagnostic-service/**
          filters:
            - StripPrefix=1
        # IAM Service - SOLO esta ruta para autenticación
        - id: iam-service-auth
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/authentication/**
          filters:
            - StripPrefix=0
        # IAM Service - registro admin
        - id: iam-service-admin-registro
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/users_admin/registro
          filters:
            - StripPrefix=0
        # Profile Service
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile-service/**, /api/v1/profiles/**
          filters:
            - StripPrefix=1

server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/