package pe.upc.pawfectcaremicroservices.medicalappointment.domain.model.valueobjects;

public enum ServiceName {
    GENERAL_MEDICINE,
    VETERINARY_SURGERY,
    VETERINARY_PATHOLOGY,
    VETERINARY_RADIOLOGY,
    VETERINARY_NUTRITION,
    VETERINARY_BEHAVIOR,
    VETERINARY_OPHTHALMOLOGY,
    VETERINARY_DERMATOLOGY,
    VETERINARY_CARDIOLOGY,
    VETERINARY_ONCOLOGY,
    VETERINARY_NEUROLOGY,
    VETERINARY_ORTHOPEDICS,
    VETERINARY_PHYSIOTHERAPY,
    EMERGENCY_AND_CRITICAL_CARE
}
