name: Build and Deploy Microservices

on:
  push:
    branches: [ deployment ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'registry', 'gateway', 'iam', 'veterinary', 'schedule',
          'pet-owner', 'pet', 'medical-record', 'appointment',
          'diagnostic', 'review'
        ]
        include:
          - service: registry
            directory: ./registry-service
            publish_profile: AZURE_PUBLISHPROFILE_REGISTRY_SERVICE
          - service: gateway
            directory: ./gateway-service
            publish_profile: AZURE_PUBLISHPROFILE_GATEWAY_SERVICE
          - service: iam
            directory: ./iam-service
            publish_profile: AZURE_PUBLISHPROFILE_IAM_SERVICE
          - service: veterinary
            directory: ./veterinary-service
            publish_profile: AZURE_PUBLISHPROFILE_VETERINARY_SERVICE
          - service: schedule
            directory: ./schedule-service
            publish_profile: AZURE_PUBLISHPROFILE_SCHEDULE_SERVICE
          - service: pet-owner
            directory: ./pet-owner-service
            publish_profile: AZURE_PUBLISHPROFILE_PET_OWNER_SERVICE
          - service: pet
            directory: ./pet-service
            publish_profile: AZURE_PUBLISHPROFILE_PET_SERVICE
          - service: medical-record
            directory: ./medical-record-service
            publish_profile: AZURE_PUBLISHPROFILE_MEDICAL_RECORD_SERVICE
          - service: appointment
            directory: ./appointment-service
            publish_profile: AZURE_PUBLISHPROFILE_APPOINTMENT_SERVICE
          - service: diagnostic
            directory: ./diagnostic-service
            publish_profile: AZURE_PUBLISHPROFILE_DIAGNOSTIC_SERVICE
          - service: review
            directory: ./review-service
            publish_profile: AZURE_PUBLISHPROFILE_REVIEW_SERVICE

    steps:
      - uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven

      - name: Compilar con Maven
        run: mvn -B package -DskipTests --file ${{ matrix.directory }}/pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.directory }}
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/pawfect-${{ matrix.service }}:${{ github.sha }}, ${{ secrets.REGISTRY_URL }}/pawfect-${{ matrix.service }}:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: pawfect-${{ matrix.service }}-service
          publish-profile: ${{ secrets[matrix.publish_profile] }}
          images: ${{ secrets.REGISTRY_URL }}/pawfect-${{ matrix.service }}:${{ github.sha }}